In [1]:
import pandas as pd
import numpy as np
branches = ['BTE', 'CHE', 'CE', 'CSE', 'EEE', 'ECE', 'ME', 'MME']
sheets = []
subjects = ['BT390', 'CH392', 'CE390', 'CS390', 'EE391', 'EC390', 'ME390', 'MM390', 'SM390', 'HS390', 'MA390', 'PH391', 'ME391']
columns = ['S.No', 'BT390', 'CH392', 'CE390', 'CS390', 'EE391', 'EC390', 'ME390', 'MM390', 'SM390', 'HS390', 'MA390', 'PH391', 'ME391']


for branch in branches:
    sheet = pd.read_excel('new_data.xlsx', sheet_name=branch)
    sheets.append(sheet)
sheets[0]

,S.No,CH392,CE390,CS390,EE391,EC390,ME390,MM390,SM390,HS390,MA390,PH391,ME391
0,0,9,2,12,4,11,6,1,7,3,10,8,5
1,1,1,10,2,9,6,12,8,11,7,3,5,4
2,2,4,2,10,9,8,11,1,6,12,7,3,5
3,3,2,4,10,12,5,8,9,1,6,7,3,11
4,4,7,10,6,11,9,12,4,3,5,8,1,2
5,5,8,12,9,1,10,2,3,4,6,5,7,11
6,6,10,2,12,5,8,6,3,4,9,11,7,1
7,7,7,4,6,1,2,5,9,11,8,3,12,10
8,8,1,3,2,10,4,6,12,9,8,7,5,11
9,9,11,3,1,9,6,12,2,10,8,4,7,5
10,10,4,3,2,11,7,1,5,9,6,12,8,10
11,11,3,6,2,4,7,10,9,11,8,12,1,5
12,12,6,4,1,12,7,3,9,5,8,10,11,2
13,13,1,7,2,5,3,12,11,10,4,6,9,8
14,14,9,10,6,5,1,2,12,4,11,3,7,8
15,15,6,7,4,9,11,1,3,8,2,5,10,12
16,16,8,6,7,10,3,2,1,9,12,5,11,4
17,17,8,2,9,11,10,12,3,4,5,6,1,7
18,18,11,12,1,3,7,2,8,10,4,5,6,9
19,19,7,5,4,8,10,11,2,9,1,3,6,12
20,20,1,10,12,9,3,8,2,11,5,4,7,6
21,21,7,12,9,5,8,3,6,4,11,2,1,10

In [2]:
for i in np.arange(len(sheets)):
    for j in subjects:
        if j not in sheets[i].columns:
            sheets[i][j] = len(sheets[i].columns)

In [3]:
sheets[6]

,S.No,BT390,CH392,CE390,CS390,EE391,EC390,MM390,SM390,HS390,MA390,PH391,ME390,ME391
0,369,2,9,6,3,7,10,5,11,4,8,1,12,13
1,370,2,8,10,6,5,11,9,3,1,4,7,12,13
2,371,7,6,9,4,11,3,10,5,2,8,1,12,13
3,372,1,6,7,11,4,8,10,9,5,3,2,12,13
4,373,11,1,9,5,10,2,8,7,4,6,3,12,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,431,10,6,5,9,7,3,8,11,1,4,2,12,13
63,432,8,11,7,5,1,4,2,3,10,6,9,12,13
64,433,11,5,8,6,9,3,4,1,10,7,2,12,13
65,434,8,2,7,5,3,6,10,9,11,4,1,12,13
66,435,5,2,11,4,3,6,8,9,10,1,7,12,13

In [4]:
new_sheets = sheets
writer = pd.ExcelWriter('new_data2.xlsx', engine='xlsxwriter')
for i in range(8):

    new_sheets[i].to_excel(writer, sheet_name=branches[i], index=False)

writer.save()

In [5]:
comdf = pd.DataFrame()
for df in new_sheets:
    comdf = pd.concat([comdf, df], ignore_index=True)

In [6]:
comdf

,S.No,CH392,CE390,CS390,EE391,EC390,ME390,MM390,SM390,HS390,MA390,PH391,ME391,BT390
0,0,9,2,12,4,11,6,1,7,3,10,8,5,13
1,1,1,10,2,9,6,12,8,11,7,3,5,4,13
2,2,4,2,10,9,8,11,1,6,12,7,3,5,13
3,3,2,4,10,12,5,8,9,1,6,7,3,11,13
4,4,7,10,6,11,9,12,4,3,5,8,1,2,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,455,4,8,12,11,6,7,13,2,5,3,9,1,10
456,456,2,1,3,4,10,6,13,11,7,12,9,8,5
457,457,4,3,7,2,5,1,13,12,10,9,8,6,11
458,458,6,7,4,12,9,3,13,11,2,5,10,8,1
459,459,10,7,3,8,2,12,13,1,4,6,5,11,9

In [7]:
from sklearn import preprocessing

x = comdf.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled, columns=columns)
x

array([[  0,   9,   2, ...,   8,   5,  13],
       [  1,   1,  10, ...,   5,   4,  13],
       [  2,   4,   2, ...,   3,   5,  13],
       ...,
       [457,   4,   3, ...,   8,   6,  11],
       [458,   6,   7, ...,  10,   8,   1],
       [459,  10,   7, ...,   5,  11,   9]])

In [8]:
df

,S.No,BT390,CH392,CE390,CS390,EE391,EC390,ME390,MM390,SM390,HS390,MA390,PH391,ME391
0,0.000000,0.666667,0.083333,0.916667,0.250000,0.833333,0.454545,0.000000,0.545455,0.181818,0.818182,0.636364,0.333333,1.000000
1,0.002179,0.000000,0.750000,0.083333,0.666667,0.416667,1.000000,0.583333,0.909091,0.545455,0.181818,0.363636,0.250000,1.000000
2,0.004357,0.250000,0.083333,0.750000,0.666667,0.583333,0.909091,0.000000,0.454545,1.000000,0.545455,0.181818,0.333333,1.000000
3,0.006536,0.083333,0.250000,0.750000,0.916667,0.333333,0.636364,0.666667,0.000000,0.454545,0.545455,0.181818,0.833333,1.000000
4,0.008715,0.500000,0.750000,0.416667,0.833333,0.666667,1.000000,0.250000,0.181818,0.363636,0.636364,0.000000,0.083333,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,0.991285,0.250000,0.583333,0.916667,0.833333,0.416667,0.545455,1.000000,0.090909,0.363636,0.181818,0.727273,0.000000,0.750000
456,0.993464,0.083333,0.000000,0.166667,0.250000,0.750000,0.454545,1.000000,0.909091,0.545455,1.000000,0.727273,0.583333,0.333333
457,0.995643,0.250000,0.166667,0.500000,0.083333,0.333333,0.000000,1.000000,1.000000,0.818182,0.727273,0.636364,0.416667,0.833333
458,0.997821,0.416667,0.500000,0.250000,0.916667,0.666667,0.181818,1.000000,0.909091,0.090909,0.363636,0.818182,0.583333,0.000000
459,1.000000,0.750000,0.500000,0.166667,0.583333,0.083333,1.000000,1.000000,0.000000,0.272727,0.454545,0.363636,0.833333,0.666667

In [9]:
comdf = df

In [10]:
 cgpa = {}

for i in range(0, 460):
    cgpa[i] = (np.random.randint(500, 1000)/100)

In [11]:
# comdf['CGPA'] = list(comdf['S.No'].map(cgpa))
comdf['CGPA'] = cgpa.values()

In [12]:
comdf

,S.No,BT390,CH392,CE390,CS390,EE391,EC390,ME390,MM390,SM390,HS390,MA390,PH391,ME391,CGPA
0,0.000000,0.666667,0.083333,0.916667,0.250000,0.833333,0.454545,0.000000,0.545455,0.181818,0.818182,0.636364,0.333333,1.000000,5.77
1,0.002179,0.000000,0.750000,0.083333,0.666667,0.416667,1.000000,0.583333,0.909091,0.545455,0.181818,0.363636,0.250000,1.000000,8.24
2,0.004357,0.250000,0.083333,0.750000,0.666667,0.583333,0.909091,0.000000,0.454545,1.000000,0.545455,0.181818,0.333333,1.000000,6.37
3,0.006536,0.083333,0.250000,0.750000,0.916667,0.333333,0.636364,0.666667,0.000000,0.454545,0.545455,0.181818,0.833333,1.000000,9.49
4,0.008715,0.500000,0.750000,0.416667,0.833333,0.666667,1.000000,0.250000,0.181818,0.363636,0.636364,0.000000,0.083333,1.000000,5.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,0.991285,0.250000,0.583333,0.916667,0.833333,0.416667,0.545455,1.000000,0.090909,0.363636,0.181818,0.727273,0.000000,0.750000,9.44
456,0.993464,0.083333,0.000000,0.166667,0.250000,0.750000,0.454545,1.000000,0.909091,0.545455,1.000000,0.727273,0.583333,0.333333,9.38
457,0.995643,0.250000,0.166667,0.500000,0.083333,0.333333,0.000000,1.000000,1.000000,0.818182,0.727273,0.636364,0.416667,0.833333,5.33
458,0.997821,0.416667,0.500000,0.250000,0.916667,0.666667,0.181818,1.000000,0.909091,0.090909,0.363636,0.818182,0.583333,0.000000,6.78
459,1.000000,0.750000,0.500000,0.166667,0.583333,0.083333,1.000000,1.000000,0.000000,0.272727,0.454545,0.363636,0.833333,0.666667,9.39

In [13]:
comdf.fillna(1, inplace=True)

In [14]:
result = {}

value = {}

for i in subjects:
    value[i] = 0

for i,row in comdf.iterrows():

    if row['S.No'] not in result:
        dictT={}
        for j in subjects:
            dictT[j] = row[j]
          
        temp = min(dictT.values())
#         print(temp)
        res = [key for key in dictT if dictT[key] == temp] 
#         res = dictT[key]
#         print(res[0])
#         print(row['S.No'])
#         print(i)
        result[i] = res[0]
        value[res[0]] += 1

In [15]:
result

{0: 'ME390',
 1: 'BT390',
 2: 'ME390',
 3: 'MM390',
 4: 'MA390',
 5: 'CS390',
 6: 'PH391',
 7: 'CS390',
 8: 'BT390',
 9: 'CE390',
 10: 'EC390',
 11: 'MA390',
 12: 'CE390',
 13: 'BT390',
 14: 'EE391',
 15: 'EC390',
 16: 'ME390',
 17: 'MA390',
 18: 'CE390',
 19: 'SM390',
 20: 'BT390',
 21: 'MA390',
 22: 'EC390',
 23: 'CH392',
 24: 'MM390',
 25: 'EC390',
 26: 'HS390',
 27: 'CS390',
 28: 'ME390',
 29: 'PH391',
 30: 'PH391',
 31: 'HS390',
 32: 'PH391',
 33: 'MA390',
 34: 'CE390',
 35: 'ME391',
 36: 'CH392',
 37: 'CS390',
 38: 'CH392',
 39: 'CE390',
 40: 'CH392',
 41: 'HS390',
 42: 'HS390',
 43: 'EC390',
 44: 'MM390',
 45: 'CS390',
 46: 'MA390',
 47: 'BT390',
 48: 'CE390',
 49: 'BT390',
 50: 'SM390',
 51: 'MM390',
 52: 'MA390',
 53: 'PH391',
 54: 'EC390',
 55: 'SM390',
 56: 'EC390',
 57: 'MA390',
 58: 'MA390',
 59: 'EE391',
 60: 'CE390',
 61: 'CS390',
 62: 'CE390',
 63: 'CS390',
 64: 'EE391',
 65: 'HS390',
 66: 'BT390',
 67: 'MM390',
 68: 'MM390',
 69: 'SM390',
 70: 'CS390',
 71: 'HS390',
 72: 'CE390',
 73: 'EE391',
 74: 'PH391',
 75: 'MA390',
 76: 'PH391',
 77: 'CS390',
 78: 'PH391',
 79: 'EC390',
 80: 'ME390',
 81: 'MA390',
 82: 'BT390',
 83: 'SM390',
 84: 'EC390',
 85: 'CS390',
 86: 'ME391',
 87: 'CS390',
 88: 'CE390',
 89: 'EE391',
 90: 'BT390',
 91: 'BT390',
 92: 'CE390',
 93: 'MM390',
 94: 'HS390',
 95: 'BT390',
 96: 'PH391',
 97: 'MA390',
 98: 'MM390',
 99: 'HS390',
 100: 'EC390',
 101: 'EE391',
 102: 'MA390',
 103: 'PH391',
 104: 'MA390',
 105: 'CS390',
 106: 'MA390',
 107: 'ME390',
 108: 'EE391',
 109: 'SM390',
 110: 'CH392',
 111: 'EC390',
 112: 'EE391',
 113: 'ME391',
 114: 'SM390',
 115: 'MM390',
 116: 'SM390',
 117: 'SM390',
 118: 'CH392',
 119: 'EC390',
 120: 'MA390',
 121: 'MM390',
 122: 'MA390',
 123: 'PH391',
 124: 'MA390',
 125: 'CS390',
 126: 'CS390',
 127: 'SM390',
 128: 'SM390',
 129: 'PH391',
 130: 'MM390',
 131: 'ME391',
 132: 'HS390',
 133: 'MM390',
 134: 'PH391',
 135: 'PH391',
 136: 'EC390',
 137: 'EC390',
 138: 'PH391',
 139: 'BT390',
 140: 'SM390',
 141: 'MA390',
 142: 'EE391',
 143: 'BT390',
 144: 'MA390',
 145: 'ME391',
 146: 'ME391',
 147: 'EC390',
 148: 'PH391',
 149: 'ME391',
 150: 'PH391',
 151: 'MA390',
 152: 'CS390',
 153: 'MA390',
 154: 'CS390',
 155: 'MM390',
 156: 'SM390',
 157: 'ME390',
 158: 'CH392',
 159: 'MM390',
 160: 'BT390',
 161: 'MM390',
 162: 'BT390',
 163: 'MA390',
 164: 'PH391',
 165: 'HS390',
 166: 'SM390',
 167: 'HS390',
 168: 'EC390',
 169: 'HS390',
 170: 'BT390',
 171: 'EC390',
 172: 'CS390',
 173: 'MA390',
 174: 'ME391',
 175: 'BT390',
 176: 'MM390',
 177: 'EC390',
 178: 'EE391',
 179: 'ME391',
 180: 'HS390',
 181: 'CS390',
 182: 'MA390',
 183: 'ME390',
 184: 'ME391',
 185: 'MM390',
 186: 'CH392',
 187: 'BT390',
 188: 'HS390',
 189: 'ME391',
 190: 'ME390',
 191: 'EE391',
 192: 'BT390',
 193: 'HS390',
 194: 'CE390',
 195: 'SM390',
 196: 'EE391',
 197: 'SM390',
 198: 'CH392',
 199: 'ME390',
 200: 'CE390',
 201: 'PH391',
 202: 'BT390',
 203: 'SM390',
 204: 'CH392',
 205: 'EE391',
 206: 'MM390',
 207: 'EC390',
 208: 'ME390',
 209: 'ME390',
 210: 'PH391',
 211: 'HS390',
 212: 'PH391',
 213: 'BT390',
 214: 'EE391',
 215: 'MM390',
 216: 'EE391',
 217: 'EC390',
 218: 'EE391',
 219: 'EC390',
 220: 'ME391',
 221: 'EC390',
 222: 'MA390',
 223: 'EC390',
 224: 'MM390',
 225: 'MA390',
 226: 'BT390',
 227: 'ME391',
 228: 'MA390',
 229: 'MM390',
 230: 'EC390',
 231: 'CE390',
 232: 'HS390',
 233: 'CE390',
 234: 'PH391',
 235: 'ME391',
 236: 'BT390',
 237: 'PH391',
 238: 'EC390',
 239: 'PH391',
 240: 'ME391',
 241: 'MM390',
 242: 'SM390',
 243: 'BT390',
 244: 'ME391',
 245: 'ME390',
 246: 'EE391',
 247: 'CH392',
 248: 'CH392',
 249: 'HS390',
 250: 'EE391',
 251: 'ME391',
 252: 'BT390',
 253: 'ME390',
 254: 'CH392',
 255: 'ME391',
 256: 'CE390',
 257: 'CE390',
 258: 'ME390',
 259: 'CH392',
 260: 'MM390',
 261: 'MA390',
 262: 'ME390',
 263: 'MM390',
 264: 'ME390',
 265: 'MM390',
 266: 'EE391',
 267: 'CH392',
 268: 'CH392',
 269: 'HS390',
 270: 'HS390',
 271: 'EE391',
 272: 'ME390',
 273: 'HS390',
 274: 'ME390',
 275: 'EC390',
 276: 'MA390',
 277: 'BT390',
 278: 'BT390',
 279: 'MM390',
 280: 'MM390',
 281: 'ME390',
 282: 'CE390',
 283: 'MA390',
 284: 'EC390',
 285: 'BT390',
 286: 'MA390',
 287: 'EC390',
 288: 'PH391',
 289: 'PH391',
 290: 'CS390',
 291: 'CE390',
 292: 'CE390',
 293: 'EC390',
 294: 'MM390',
 295: 'MM390',
 296: 'BT390',
 297: 'BT390',
 298: 'MA390',
 299: 'CE390',
 300: 'CH392',
 301: 'MM390',
 302: 'SM390',
 303: 'MA390',
 304: 'MM390',
 305: 'CE390',
 306: 'MA390',
 307: 'PH391',
 308: 'PH391',
 309: 'ME391',
 310: 'ME390',
 311: 'CS390',
 312: 'BT390',
 313: 'CS390',
 314: 'CS390',
 315: 'EC390',
 316: 'MM390',
 317: 'SM390',
 318: 'EC390',
 319: 'SM390',
 320: 'BT390',
 321: 'CE390',
 322: 'CH392',
 323: 'CS390',
 324: 'CS390',
 325: 'ME391',
 326: 'PH391',
 327: 'MM390',
 328: 'EC390',
 329: 'CE390',
 330: 'MM390',
 331: 'PH391',
 332: 'ME391',
 333: 'SM390',
 334: 'CE390',
 335: 'MM390',
 336: 'CE390',
 337: 'MM390',
 338: 'BT390',
 339: 'CE390',
 340: 'CE390',
 341: 'CH392',
 342: 'ME390',
 343: 'CS390',
 344: 'MA390',
 345: 'CH392',
 346: 'SM390',
 347: 'MA390',
 348: 'HS390',
 349: 'ME391',
 350: 'MA390',
 351: 'MA390',
 352: 'MM390',
 353: 'MA390',
 354: 'CS390',
 355: 'HS390',
 356: 'CE390',
 357: 'HS390',
 358: 'HS390',
 359: 'SM390',
 360: 'CS390',
 361: 'MA390',
 362: 'EC390',
 363: 'CS390',
 364: 'ME390',
 365: 'CH392',
 366: 'EC390',
 367: 'CH392',
 368: 'PH391',
 369: 'MA390',
 370: 'SM390',
 371: 'MA390',
 372: 'ME391',
 373: 'BT390',
 374: 'HS390',
 375: 'CH392',
 376: 'ME391',
 377: 'MA390',
 378: 'CE390',
 379: 'CS390',
 380: 'HS390',
 381: 'CS390',
 382: 'CH392',
 383: 'ME390',
 384: 'CH392',
 385: 'EE391',
 386: 'CH392',
 387: 'ME391',
 388: 'CS390',
 389: 'CE390',
 390: 'CH392',
 391: 'CE390',
 392: 'CE390',
 393: 'HS390',
 394: 'HS390',
 395: 'CE390',
 396: 'SM390',
 397: 'ME390',
 398: 'EE391',
 399: 'MA390',
 400: 'HS390',
 401: 'HS390',
 402: 'CE390',
 403: 'HS390',
 404: 'ME391',
 405: 'CS390',
 406: 'HS390',
 407: 'EE391',
 408: 'HS390',
 409: 'HS390',
 410: 'CE390',
 411: 'HS390',
 412: 'CH392',
 413: 'CS390',
 414: 'MM390',
 415: 'CS390',
 416: 'MA390',
 417: 'CS390',
 418: 'SM390',
 419: 'ME391',
 420: 'BT390',
 421: 'EE391',
 422: 'CH392',
 423: 'EE391',
 424: 'HS390',
 425: 'ME391',
 426: 'HS390',
 427: 'ME390',
 428: 'CE390',
 429: 'HS390',
 430: 'MM390',
 431: 'SM390',
 432: 'CS390',
 433: 'MM390',
 434: 'MA390',
 435: 'HS390',
 436: 'BT390',
 437: 'ME391',
 438: 'EC390',
 439: 'HS390',
 440: 'BT390',
 441: 'EC390',
 442: 'EC390',
 443: 'HS390',
 444: 'SM390',
 445: 'BT390',
 446: 'MM390',
 447: 'PH391',
 448: 'MM390',
 449: 'CH392',
 450: 'SM390',
 451: 'MA390',
 452: 'MM390',
 453: 'CE390',
 454: 'MA390',
 455: 'PH391',
 456: 'CH392',
 457: 'EC390',
 458: 'ME391'}